codecov:
  token: 11c28e95-6e64-4829-9887-04e4cd661bf6
  comment:
    after_n_builds: 8

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 10%
        informational: true
